
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/workshop?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: workshop2021

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true